FROM nvidia/cuda:11.1.1-cudnn8-runtime-ubuntu18.04

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PATH /opt/conda/bin:$PATH
COPY requirements-cuda.txt .

# Install Dependencies of Anaonda
 RUN apt-get update --fix-missing && \
     apt-get install -y wget bzip2 curl git && \
     apt-get clean && \
     rm -rf /var/lib/apt/lists/*

# Istall Anconda3 and make conda enviroment
RUN wget --quiet https://repo.anaconda.com/archive/Anaconda3-5.2.0-Linux-x86_64.sh -O ~/conda.sh && \
    /bin/bash ~/conda.sh -b -p /opt/conda && \
    rm ~/conda.sh && \
    /opt/conda/bin/conda clean -tipsy && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    conda update conda && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc

#Build Deepfacelab Anaconda enviroment
RUN conda create -y --name deepfacelab python=3.7 tensorflow-gpu
RUN . /opt/conda/etc/profile.d/conda.sh && conda activate deepfacelab && \
    pip install --upgrade pip && \
    apt update && \
    apt-get install -y libsm6 libxext6 libxrender-dev libglib2.0-0 && \
    python -m pip install -r requirements-cuda.txt && \
    pip install opencv-python


RUN echo "conda activate deepfacelab" >> ~/.bashrc